Feature async
radical-collaboration/DeepDriveMD pull request #14
Opened 2024-12-09 18:39 UTC by okilic1

Creating PR for new DDMD folder

2024-12-10 00:58 UTC, andre-merzky approved these changes

2024-12-10 04:13 UTC, mtitov requested changes

2024-12-10 04:13 UTC, mtitov commented on .DS_Store
this shouldn't be committed

2024-12-10 04:13 UTC, mtitov commented on .DS_Store
would be good to add a corresponding `.gitignore` file

2024-12-10 04:13 UTC, mtitov commented on README.md
> +This is an on going develeopment branch  you can find the source code under [src](https://github.com/radical-collaboration/DeepDriveMD/tree/master/src/) and [data](https://github.com/radical-collabor
`ongoing`

2024-12-10 04:13 UTC, mtitov commented on README.md
> +# Asyncronous Execution Development published at JSSPP
`Asynchronous`

2024-12-10 04:13 UTC, mtitov commented on README.md
> +## COVID-19 Development (Relocated under [archive](https://github.com/radical-collaboration/DeepDriveMD/tree/master/archive)
missing closing `)`

2024-12-10 04:13 UTC, mtitov commented on archive
do I miss something - isn't this folder should contain the previous content of this repo?

2024-12-10 04:13 UTC, mtitov commented on docs/algorithm.md
all these deleted files - should they be moved and not deleted?

2024-12-10 04:18 UTC, mtitov commented on archive
ah, understood what it is - link to the branch `archive`, but does it work?

2024-12-18 13:56 UTC, okilic1 commented on .DS_Store
Done

2024-12-18 13:56 UTC, okilic1 commented on README.md
> +This is an on going develeopment branch  you can find the source code under [src](https://github.com/radical-collaboration/DeepDriveMD/tree/master/src/) and [data](https://github.com/radical-collabor
Done

2024-12-18 13:57 UTC, okilic1 commented on README.md
> +# Asyncronous Execution Development published at JSSPP
Done

2024-12-18 13:57 UTC, okilic1 commented on README.md
> +## COVID-19 Development (Relocated under [archive](https://github.com/radical-collaboration/DeepDriveMD/tree/master/archive)
Done

2024-12-20 14:00 UTC, mtitov commented on .DS_Store
added file is empty

2024-12-20 14:03 UTC, mtitov commented
Proposal to use a tag for an archived branch.

2024-12-23 12:50 UTC, okilic1 commented on .DS_Store
I added content in it

2024-12-23 16:26 UTC, mtitov approved these changes

2025-01-08 13:52 UTC, merged